### ISSUE TITLE
I can launch two or three jobs at the same time by clicking a square lots!

### ISSUE THREAD

**Issue by mirams** [ModellingWebLab/WebLab#105]
Should only allow one...

Child of #68.

**Comment by jonc125** [comment]
This might be to do with the launch running in a database transaction, so if you click twice the second launch doesn't actually know about the first one because it hasn't completed the REST call to the backend yet.

**Comment by jonc125** [comment]
Or possibly on `RunningExperiment` we just need to make the foreign key to `ExperimentVersion` unique, so the DB errors if you try to run twice. We'd then need to let submit_experiment catch this error - or perhaps better, return the already-created version? (I.e. do a `get_or_create` rather than `create`.)
