### ISSUE TITLE
Unnecessary use of 'Commit' objects in views

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/WebLab#191]
There are several places in code where we use something like
                entity.repo.get_commit(version.sha))
 and pass the resulting commit object to an html view. Here it used to extract information about the commit - author/date/numfiles etc but there is no need for actual commit object. Since every commit records some information in the repocache surely it would be better to extend the information stored (some is there - some is not) so that there is no need to grab the actual commit.

What particularly confuses me is that the commit object gets passed to the url functions which seem to then create url based on tag if it exists or a reduced version of the sha. I haven't worked out the logic of this - but that also seems overkill for creating a url. The appropriate string is what is needed.

Note: I am talking only about views since these do not actually use anything other than attributes of the Commit. I realise other things may need the whole thing.

Disclaimer: I might be missing something crucial :-)

**Comment by jonc125** [comment]
As suggested above, what we want to do here is replace most uses of the actual `entities.repository.Commit` objects with `repocache.CachedEntityVersion`, extending the information stored there as necessary, so that everything that doesn't absolutely require hitting the disk (like reading a file's content, or adding a new commit) can work just with the DB cache. Also, the `CachedEntityVersion` API should be updated to match (i.e. use the same names as) the `Commit` class.

**Comment by jonc125** [comment]
In #234 I've been spotting uses of `Commit` that we might want to replace (and adding TODO comments appropriately). So once the cache changes have been done we might want to review & merge #222 and #234 before continuing with this issue?

But there's also a discussion point from my latest commit. The JSON views for entities include info about file names & sizes. When you're viewing a single version it's not a big issue to get the full commit data. But for *comparing* you might be accessing several commits. However, this is just the comparison of model or protocol definitions, so the number of commits tends to be small, and typically all within the same repo (unlike for experiment result comparisons). So I'm still not sure it's worth caching the file names & sizes. Perhaps just leave as a note for future consideration if it turns out to be a performance issue?

**Comment by sroderick-g5sro** [comment]
It does seem that we only need the number of files rather than the full filenames. Shall I add numfiles as a new db field? not sure about the ephemeral_files. Do I need any special processing to handle these?

**Comment by jonc125** [comment]
Yes, just add a `numfiles` field to the cache. You shouldn't need to do anything special with the ephemeral files, just look at `len(commit.filenames)`.
