### ISSUE TITLE
Add option to delete account

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#192]
https://scrambler.cs.ox.ac.uk/privacy

> We will be adding the facility to delete your account shortly.

**Comment by jonc125** [comment]
I'm pretty sure we can already do it manually via the admin interface, though it might not cascade to delete all the stuff they own; not sure!

**Comment by jonc125** [comment]
There's a question over what we should delete actually. I think it's fairly obvious that all models, protocols, fitting specs & datasets uploaded by the user should be deleted. And so all experiment runs using one of them should also be deleted. But should an experiment involving only entities owned by other users be deleted?

If not life gets a bit trickier, because currently an `Experiment` has an `author` foreign key pointing at the user who ran it, with a default `on_delete=CASCADE`, so the experiments the user ran will be deleted by default. We'd need to move experiments to another user to avoid this, and it's debatable which user should be chosen!
