### ISSUE TITLE
Allow deletion of entities and files

### ISSUE THREAD

**Issue by helenst** [ModellingWebLab/WebLab#22]
Deleting an entity should destroy the local repository (probably with a warning)
Deleting a file should be part of a new version of the model, with a corresponding commit.

**Comment by jonc125** [comment]
For deleting a file, would we want a shortcut 'delete' action for individual files? I suspect not - rather it should be possible as part of the normal 'new version' process that you can delete existing files as well as add new ones (and replace existing ones). Would you agree @mirams @MichaelClerx ?

**Comment by mirams** [comment]
Might not be obvious that you have to create a new version to delete a file? Although deleting whole files without changing anything else would be unusual unless you wanted to delete the whole entity I suppose.

**Comment by jonc125** [comment]
That was my feeling. And you'd need to give a commit comment etc.

**Comment by MichaelClerx** [comment]
How is this 'new version' user presented to the user?

In git, I just delete a file and then _later_ it tells me that this is no longer the same set of files I had before. That seems the straightforward way to me. We wouldn't want users to have to specifiy 'new version' themselves for every action on an entity/repo?

**Comment by jonc125** [comment]
The new version UI is a bit flaky at present, as noted in #21. But I don't think we need to restrict ourselves to following the git workflow - it doesn't necessarily make sense for a web interface. Any edits to the files (whether changing a file contents, or adding/removing files) requires creating a new version, and doing that from one page rather than trying to track what's happening over multiple page loads is much easier to manage I reckon.

We could certainly make the 'new version' link more obvious. And we could have a 'delete file' action that takes you to the new version page with the file marked deleted, if this is thought to be a common action?

**Comment by helenst** [comment]
I think having the 'delete file' lead through to a new version page (so a new file could be added at the same time) makes a lot of sense. It will require a new commit on the git backend, but it can be written so that the user doesn't have to actively think about that when deciding to delete a file.

**Comment by helenst** [comment]
- [ ] Entity deletion
- [ ] File deletion
