### ISSUE TITLE
Improvements to entity upload & display

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#27]
Child of #12 with minor issues that didn't need to be addressed in #21.

- [x] The 'Version' field should now be optional I think. It's basically a git tag isn't it?
- [x] So rename to 'Tag' to make that clearer.
- [x] I'm not sure I like displaying the full SHA for a version. Perhaps do this only if there isn't a tag, and just show the tag otherwise? And/or show just the first 8 characters?
- [x] I like that you can use the tag in the URL though! Add a test to check this keeps working.
- [x] The versions list should show the commit message. (Or at least, the first line. I'm not sure if or where to display a longer message.)
- [x] Make the visibility status display more like the original Web Lab
- [x] Improve hover text on new version form
- [x] When generating URLs, supply a tag instead of SHA if present?
- [x] Show all tags associated with a commit (will do this in a separate PR I think)
- [x] Allow adding a tag to a version after creation (may become separate issue/PR if non-trivial)

Thoughts @mirams @MichaelClerx ?

**Comment by MichaelClerx** [comment]
+1 for renaming version 'tag'. We should be very careful in how we use the word version with this internal repo stuff going on. Esp. for people who won't be familiar with version control (and so will have it on their mind when they're reading web lab docs) (and I think the number of people not familiar with version control will be substantial)

**Comment by MichaelClerx** [comment]
First 8 characters seems to work well for github!

**Comment by MichaelClerx** [comment]
Longer messages (and full hashes) could go in a (hover) tooltip*?
(*As long we make sure the info is never essential, so it's not an issue for keyboard fans, screen readers etc)

**Comment by mirams** [comment]
Happy with 'Tag' rather than 'Version' as I am warming to git and it seems to be the thing for the foreseeable future.

I think forcing a user-friendly name as a tag makes sense, or defaulting to date and time like we do now. I am getting weary of SHAs and not being able to see at a glance what is old and what is new!

Is there somewhere to look at the prototype?

**Comment by jonc125** [comment]
At the moment the prototype isn't deployed anywhere, so you need to run it locally on your machine. We could look into putting a test instance on scrambler?

**Comment by MichaelClerx** [comment]
Yup! Would be interested in seeing how that works :-) :-)

Tags are usually associated with releases, right? So we'd have unnamed 'hash' versions of models and then occasional named releases? Might be a good thing, as a big ugly hash as name would make it obvious some research was using a development version of a model. On the other hand, people might be hesitant to every finalise a model?

**Comment by jonc125** [comment]
Can we get consensus on the optional tag question? How useful is it to require a tag for every version? We could do date+time, but this is already available from the creation timestamp and displayed on the version screen.

We also have the commit message for longer explanations of what's changed in each version. (Do we want a better name for that, incidentally?)

One potential issue is that people may not know when they create a new version if this is the 'final working version'. So being able to tag after the fact may be useful!

**Comment by MichaelClerx** [comment]
So we'd like to...
- stay close to git / avoid re-implementing things
- be able to see at a glance what is old and new. I guess this includes urls? If so, that'd mean we can't use the git hash as a unique id in the system, and would have to have a second, human-readable one.
- be able to add tags as "special" labels, after they've already been published

So that would mean implementing a secondary unique id system then? @mirams ?

**Comment by jonc125** [comment]
I don't see why there's an issue using the sha as unique id? URLs can currently identify version by sha, tag (if it exists) or 'latest'.

**Comment by MichaelClerx** [comment]
Is that not what Gary was saying?

> I think forcing a user-friendly name as a tag makes sense, or defaulting to date and time like we do now. I am getting weary of SHAs and not being able to see at a glance what is old and what is new!

**Comment by jonc125** [comment]
We could create an integer id from the index of a commit in the list (or actually len-index since the list is newest first). But then you need to iterate all commits every time you want to look one up, which isn't ideal.

**Comment by mirams** [comment]
I am leaning towards not requiring a tag, so that in future other tools etc. could press a 'clone' button like on github and do whatever they want in standard git, and we could merge it all back in and be able to view any legal git tree in WebLab if we want (including nodes without tags).

I can probably live with seeing hashes as long as lists of commits have time stamps too.

No problem with adding a tag to something that didn't have one. But adding a tag to something that already had one would mean either: 
 * two tags pointing to the same hash commit, which would be a bit odd but OK I suppose. Since the URLs are already redundant with sha/tag/latest, this would be sha/tag1/tag2/latest. Guess this is what git branches effectively do like `master`,`release`,`develop` pointing to the same commit on Chaste git. So we'd want to order lists of versions like git nodes and display all tags next to them.
 * Or removing the old tag, which would mean some URLs go stale or could end up pointing to different things, which we should avoid.

**Comment by mirams** [comment]
I'm even going a bit mad and imagining every one of these repos living on github so people / web-lab can do push and pull requests like people are now used to, and Web Lab just goes and digs things out of there to run experiments... but I think I have maybe not had enough sleep recently.

**Comment by MichaelClerx** [comment]
That sounds like a perfectly valid approach to me!

So just hashes and tags a la github then?

**Comment by jonc125** [comment]
Ooh, not sure what happens if you have 2 tags for a commit! I'll check that...

**Comment by jonc125** [comment]
At present if you have multiple tags for a commit, all of them can be used to find that commit, but only the most recently added gets shown. Do we want to show all tags for a commit?

**Comment by MichaelClerx** [comment]
I think so! I can imagine tagging something as a release, but then also as a version used in a paper...

**Comment by jonc125** [comment]
As well as adding tags, do we want to allow people to remove them?

**Comment by mirams** [comment]
Definitely - I just used the Web Lab for this to get a newly annotated model with non-standard metadata back to our accepted set so I could use it in Chaste.!

**Comment by jonc125** [comment]
Closing this as everything seems to be done for now. We can open new issues if there are other improvements to be made.
