### ISSUE TITLE
Improvements to entity view

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/WebLab#35]
Related to #12 & #24. I think we discussed these already somewhere but can't find it!

- [ ] Rename the 'version' field to 'tag' and perhaps make it optional - opinions @mirams  @MichaelClerx ?
- [ ] I'm not sure I like displaying the full SHA for a version so prominently. Perhaps use (a shortened version of) this only if there isn't a tag? And have it as a tooltip on the tag/shortened text otherwise?

**Comment by jonc125** [comment]
Ah, found it now! #27...

**Comment by mirams** [comment]
Happy with 'Tag' rather than 'Version' as I am warming to git and it seems to be the thing for the foreseeable future.

I think forcing a user-friendly name as a tag makes sense, or defaulting to date and time like we do now. I am getting weary of SHAs and not being able to see at a glance what is old and what is new!

Is there somewhere to look at the prototype?
